// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7_7A2BnM-aB8GoNdREb_0EqlSzVeeDt0',
    appId: '1:1010964968586:web:8f3322b0f2904f6f1de973',
    messagingSenderId: '1010964968586',
    projectId: 'ddd-with-riverpod',
    authDomain: 'ddd-with-riverpod.firebaseapp.com',
    storageBucket: 'ddd-with-riverpod.appspot.com',
    measurementId: 'G-X4FEGZWMKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwqwZz4UXA-xQHxH4zPDtgfANMmh_P1Uc',
    appId: '1:1010964968586:android:e04440552d7aabc01de973',
    messagingSenderId: '1010964968586',
    projectId: 'ddd-with-riverpod',
    storageBucket: 'ddd-with-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALF8h8VZ0ya8tqIuS6H9hl8K4CCQfM7_g',
    appId: '1:1010964968586:ios:ce6676b8ed8de2d81de973',
    messagingSenderId: '1010964968586',
    projectId: 'ddd-with-riverpod',
    storageBucket: 'ddd-with-riverpod.appspot.com',
    iosClientId: '1010964968586-t72ij761pnld2vta1im7agoglr2ii7qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.dddRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALF8h8VZ0ya8tqIuS6H9hl8K4CCQfM7_g',
    appId: '1:1010964968586:ios:ce6676b8ed8de2d81de973',
    messagingSenderId: '1010964968586',
    projectId: 'ddd-with-riverpod',
    storageBucket: 'ddd-with-riverpod.appspot.com',
    iosClientId: '1010964968586-t72ij761pnld2vta1im7agoglr2ii7qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.dddRiverpod',
  );
}
